INSERT INTO TB_APPPARAMETERS (ID_APPPARAMETER, NAME, VALUE_PARAM) VALUES (1, 'LONGEVIDAD_GLOBAL', '70');

INSERT INTO TB_CLIENT (ID_CLIENT, NAME, LASTNAME, AGE, BIRTHDATE) VALUES (1, 'Sergio', 'Ramírez', 25, '1999-09-11');
INSERT INTO TB_CLIENT (ID_CLIENT, NAME, LASTNAME, AGE, BIRTHDATE) VALUES (2, 'Darío', 'Ramírez', 27, '1997-08-23');
INSERT INTO TB_CLIENT (ID_CLIENT, NAME, LASTNAME, AGE, BIRTHDATE) VALUES (3, 'Laura', 'Ramírez', 29, '1995-01-17');
INSERT INTO TB_CLIENT (ID_CLIENT, NAME, LASTNAME, AGE, BIRTHDATE) VALUES (4, 'Tomás', 'Campos', 26, '1998-09-11');
INSERT INTO TB_CLIENT (ID_CLIENT, NAME, LASTNAME, AGE, BIRTHDATE) VALUES (5, 'Eliana', 'Ramírez', 35, '1989-09-11');

ALTER TABLE TB_CLIENT ALTER COLUMN ID_CLIENT RESTART WITH 6;
